### ISSUE TITLE
Out of date with current libgphoto2

### ISSUE THREAD

**Issue by ryanstout** [zaeleus/ffi-gphoto2#5]
First, thanks for this gem.

I'm seeing a lot of errors with the latest libgphoto2.  Any interest in updating things?  (I would be willing to throw a little money behind a bug bounty if you wanted ($200?))

Thanks!

**Comment by zaeleus** [comment]
I can take a look.

I'm not getting any errors with libgphoto2 2.5.9, libgphoto2_port 0.12.0, ffi-gphoto2 0.5.1, and a Nikon D5100, so can you paste your output? There is a private `DEBUG` env variable to dump function calls and return codes, e.g., `DEBUG=1 ruby capture.rb`.

**Comment by ryanstout** [comment]
Strange, I'm seeing a lot of errors, but maybe they are all related.  So for example, when I capture, if it can't focus I get the following:

```
RuntimeError: Unspecified error (-1)
	from /var/lib/gems/1.9.1/bundler/gems/ffi-gphoto2-fa73483f0d3a/lib/gphoto2.rb:53:in `check!'
	from /var/lib/gems/1.9.1/bundler/gems/ffi-gphoto2-fa73483f0d3a/lib/gphoto2/camera/capture.rb:51:in `_capture'
	from /var/lib/gems/1.9.1/bundler/gems/ffi-gphoto2-fa73483f0d3a/lib/gphoto2/camera/capture.rb:15:in `capture'
	from (irb):5
	from /var/lib/gems/1.9.1/gems/bundler-1.11.2/lib/bundler/cli/console.rb:14:in `run'
	from /var/lib/gems/1.9.1/gems/bundler-1.11.2/lib/bundler/cli.rb:319:in `console'
	from /var/lib/gems/1.9.1/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/1.9.1/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/1.9.1/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
	from /var/lib/gems/1.9.1/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
	from /var/lib/gems/1.9.1/gems/bundler-1.11.2/lib/bundler/cli.rb:10:in `start'
	from /var/lib/gems/1.9.1/gems/bundler-1.11.2/exe/bundle:19:in `block in <top (required)>'
	from /var/lib/gems/1.9.1/gems/bundler-1.11.2/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
	from /var/lib/gems/1.9.1/gems/bundler-1.11.2/exe/bundle:17:in `<top (required)>'
	from /usr/local/bin/bundle:23:in `load'
	from /usr/local/bin/bundle:23:in `<main>'
```

**Comment by ryanstout** [comment]
(on a nikon d810 if it matters)

**Comment by zaeleus** [comment]
Okay, I can reproduce that. It does look like [a failed autofocus is indeed an error](https://github.com/gphoto/libgphoto2/blob/0b93d2bedc185c0236310531d56ab4be43a4fd1c/camlibs/ptp2/library.c#L2883) on Nikon cameras, and the error code from the camera [gets lost going up libgphoto2](https://github.com/gphoto/libgphoto2/blob/0b93d2bedc185c0236310531d56ab4be43a4fd1c/camlibs/ptp2/library.c#L134-L150), which is why it's spitting out "Unspecified error (-1)".

```
3.327374 ptp_usb_getresp [usb.c:428] (0): PTP_OC 0x9207 receiving resp failed: Out of Focus (0xa002)
3.327385 camera_nikon_capture [library.c:2857](0): 'ret' failed: 'Out of Focus' (0xa002)
3.327393 gp_context_error            (0): Out of Focus
```

I think the workaround will be to loop autofocus until it's successful before capture (the `autofocusdrive` config key on Nikon cameras), but I'll check if the camera emits some sort of event first.

**Comment by ryanstout** [comment]
thanks.  Let me keep messing with things, there's a few other errors I've been seeing, but maybe its related.

**Comment by zaeleus** [comment]
This autofocus loop seems to work. You may want to keep count and timeout if it's continuously unsuccessful.

```ruby
GPhoto2::Camera.first do |camera|
  begin
    camera.update(autofocusdrive: true)
  rescue RuntimeError
    camera.reload
    retry
  ensure
    camera.update(autofocusdrive: false)
  end

  camera.capture
end
```

**Comment by zaeleus** [comment]
I'm closing this issue due to inactivity, but feel free to reopen it or create a new one if you still have questions.
